#!/bin/bash

set -euo pipefail

source lib/log.sh

log_info "Starting: janus"

source lib/system.sh 
source lib/packages.sh
source lib/aur.sh
source lib/ssh.sh
source lib/dotfiles.sh
source lib/tailscale.sh

rm --force --recursive $HOME/janus

log_info "Finished: janus"
