#!/bin/bash

set -euo pipefail

source lib/log.sh
source detect/system.sh 
source detect/hardware.sh
source setup/aur.sh
source setup/ssh.sh
source packages/drivers.sh
source packages/base.sh
source packages/development.sh
source packages/aur.sh
source packages/gaming.sh
source setup/git.sh
source setup/tailscale.sh
source setup/dotfiles.sh

log_info "finished"

rm -rf ~/janus
